export const SERVER_STATE_LOADED = "SERVER_STATE_LOADED"
export const SERVER_STATE_LOAD_FAILED = "SERVER_STATE_LOAD_FAILED"

export const REQUEST_ACCEPTED_BY_SERVER = "REQUEST_ACCEPTED_BY_SERVER"
export const REQUEST_REJECTED_BY_SERVER = "REQUEST_REJECTED_BY_SERVER"
